name: Deploy Infrastructure

# https://docs.github.com/en/actions/how-tos/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

on:
  # Allow triggering manually for easier testing
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      matrix:
        region:
          - eu-central-1
    uses: ./.github/workflows/deploy-region.yml
    with:
      aws-region: ${{ matrix.region }}
    secrets: inherit
