name: Deploy Infrastructure

on:
  # Allow triggering manually for easier testing
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      matrix:
        region:
          - eu-central-1
    uses: ./.github/workflows/deploy-region.yml
    with:
      aws-region: ${{ matrix.region }}
