name: Deploy Infrastructure

on:
  # Allow triggering manually for easier testing
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region:
          - eu-central-1

    steps:
      - name: Call deploy-infra workflow for ${{ matrix.region }}
        uses: ./.github/workflows/deploy-region.yml
        with:
          aws-region: ${{ matrix.region }}
